### ISSUE TITLE
Compile problem from DMD change (primitive types match to alias template parameter)

### ISSUE THREAD

**Issue by FeepingCreature** [dlang-community/mecca#17]
Over at dlang/dmd I've submitted https://github.com/dlang/dmd/pull/9769 , which makes template alias parameters match primitive types as well. This runs into a buildkite problem while building mecca: https://buildkite.com/dlang/dmd/builds/6470#ddea912b-dcd7-46ce-9e63-575e6a5d3701 where presumably a `void delegate()` argument started matching to an `alias` template parameter that it did not used to. Any chance you can preemptively fix this on your end so that my PR would be green? You'd probably have to check that the alias parameter actually is a callable such as a lambda or nested function, and not just a delegate _type_.

**Comment by JohanEngelen** [comment]
Can fix, but I prefer if you to fix it (or someone with dmd+your PR). It'd be a good check to see how hard it is to locate and fix the introduced breakage.

**Comment by FeepingCreature** [comment]
Sure, PR up. edit: Merged.

**Comment by FeepingCreature** [comment]
Could we get a tag for this version please? The CI doesn't build master, so my DMD PR is still red.

**Comment by EyalIO** [comment]
Tagged v0.0.11
